// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTs1aKf3DcETYk3cW4kRy8E0Y6UZm_wBw',
    appId: '1:987583801153:web:ee689ead3e5ce0b30f23c0',
    messagingSenderId: '987583801153',
    projectId: 'dairyongo',
    authDomain: 'dairyongo.firebaseapp.com',
    storageBucket: 'dairyongo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi7T5lNuzVAW88jDNMJRvJoWU2KIle2q0',
    appId: '1:987583801153:android:5392ccbba71198260f23c0',
    messagingSenderId: '987583801153',
    projectId: 'dairyongo',
    storageBucket: 'dairyongo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9ThItE3aMwT_4vm8zhWxRGf4jIXmBl5o',
    appId: '1:987583801153:ios:0e240867f987ad850f23c0',
    messagingSenderId: '987583801153',
    projectId: 'dairyongo',
    storageBucket: 'dairyongo.appspot.com',
    iosClientId: '987583801153-u352n9fant27f7kqlsfjuiea10lgl6s9.apps.googleusercontent.com',
    iosBundleId: 'com.example.dairyongo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9ThItE3aMwT_4vm8zhWxRGf4jIXmBl5o',
    appId: '1:987583801153:ios:0e240867f987ad850f23c0',
    messagingSenderId: '987583801153',
    projectId: 'dairyongo',
    storageBucket: 'dairyongo.appspot.com',
    iosClientId: '987583801153-u352n9fant27f7kqlsfjuiea10lgl6s9.apps.googleusercontent.com',
    iosBundleId: 'com.example.dairyongo',
  );
}
